# -*- coding: utf-8 -*-
"""Elkom 1 - Modul 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_WBijqXerkHDTr-DEMGHAonMWttlshe
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

import pandas as pd
#from pandas.tools import plotting
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier,export_graphviz
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier

data_quina = pd.read_csv('/content/houseprice (1).csv', sep = ';')
data_quina.head(5)

#boxplot dari harga rumah/price
col_list=['Price']
numhouse = data_quina[data_quina.columns[data_quina.columns.isin(col_list)]]
plt.figure(figsize=(10,5))
numhouse.boxplot(sym='r*', grid=False)
plt.show()

#hist dari Price
plt.figure(figsize=(15,5))
plt.subplot(121)
data_quina['Price'].plot.hist(bins=10, title='Price')
plt.show()

#scatter dari price
col_list=['Price', 'SqFt']
numhouse = data_quina[data_quina.columns[data_quina.columns.isin(col_list)]]
numhouse.plot.scatter(x='SqFt', y='Price')

#boxplot grouped berdasarkan bedrooms
col_list=['Price', 'Bedrooms']
numhouse = data_quina[data_quina.columns[data_quina.columns.isin(col_list)]]
plt.figure(figsize=(15,5))
numhouse.boxplot(by='Bedrooms')
plt.show()